DROP TABLE IF EXISTS NP_OUTAGE_AFFECTED_LID;
  CREATE TABLE NP_OUTAGE_AFFECTED_LID 
   (	OUTAGE_ID VARCHAR(20) , 
	    LID VARCHAR(8), 
	    CHANGE_TYPE VARCHAR(20), 
	    UPD_TIME DATE,
	    PRIMARY KEY(OUTAGE_ID, LID));
	    
DROP TABLE IF EXISTS NP_OUTAGE_INFO;	    
CREATE TABLE NP_OUTAGE_INFO 
   (	
    ID VARCHAR(200) PRIMARY KEY, 
	START_DATE DATETIME , 
	END_DATE DATETIME , 
	NEXT_STATUS_DATE DATETIME , 
	EXPECTED_SOLVED_DATE DATETIME , 
	TYPE VARCHAR(20), 
	TITLE VARCHAR(2000), 
	SEVERITY VARCHAR(50), 
	KABBLING VARCHAR(20), 
	STATUS VARCHAR(100), 
	MAIN_SERVICE_AFFECTED VARCHAR(200), 
	SUB_SERVICE_AFFECTED VARCHAR(200), 
	TECHNOLOGY VARCHAR(20), 
	IMPACTED_CUSTOMERS_COUNT INT, 
	DESCRIPTION VARCHAR(2000), 
	EXTERNAL_TEXT_TITLE_DANISH VARCHAR(2000), 
	EXTERNAL_TEXT_DANISH VARCHAR(2000), 
	EXTERNAL_TEXT_TITLE_ENGLISH VARCHAR(2000), 
	EXTERNAL_TEXT_ENGLISH VARCHAR(2000), 
	INCIDENT_OWNER VARCHAR(200), 
	AREA VARCHAR(2000), 
	CONTACT_INFORMATION VARCHAR(200), 
	DOMAIN VARCHAR(200), 
	UPD_DATE DATE, 
	CHANGE_TYPE VARCHAR(20), 
	NETWORK_PROVIDER VARCHAR(200), 
	CREATE_DATE DATE);
	
DROP TABLE IF EXISTS NP_OUTAGE_OLD_VALUES;
   CREATE TABLE NP_OUTAGE_OLD_VALUES 
   (	
   	OUTAGE_ID VARCHAR(20), 
	FIELD_NAME VARCHAR(40), 
	VALUE VARCHAR(2000), 
	TIMESTAMP DATE, 
	CHECKBOX_NAME VARCHAR(10), 
	CHECKBOX_CHECKED INT, 
	PRIMARY KEY(OUTAGE_ID, FIELD_NAME));
	
DROP TABLE IF EXISTS NP_OUTAGE_REQ_RESP_LOG;	
  CREATE TABLE NP_OUTAGE_REQ_RESP_LOG 
   (	
    ID INT AUTO_INCREMENT  PRIMARY KEY, 
	REQ CLOB, 
	RESP VARCHAR(2000), 
	SYSTIME DATE, 
	OUTAGEID VARCHAR(200)
  )